### ISSUE TITLE
permissions not working when applied to the groups

### ISSUE THREAD

**Issue by vaniron** [Daniel-Forge-Development/ForgeTAB#1]
prefix/suffix does not work if permission is set in luckperms group (works fine if applied directly to the user), for example:

lp user VanironCZ permission set tab.vedeni - working
lp group vedeni permission set tab.vedeni - not working

**Comment by HackuJacku** [comment]
Tested this and it works fine. You need your lowest group (e.g: default) to have the highest weight and the highest group (e.g: owner) to have the lowest weight
